### ISSUE TITLE
Fixing labels

### ISSUE THREAD

**Issue by GneyHabub** [GneyHabub/SWProject#5]
На самом деле я просто практикуюсь работать с гитом))
Но и лейблы тоже фиксить надо

**Comment by pollytur** [comment]
I have fixed - now all ids are unique in html, please check if it works as you expected after I will put my changes in a pull request

**Comment by GneyHabub** [comment]
Labels still work incorrectly.

**Comment by pollytur** [comment]
I have not committed yet) There occurred some problems with log in
