### ISSUE TITLE
Add new pages to the Django

### ISSUE THREAD

**Issue by GneyHabub** [GneyHabub/SWProject#6]
Я сверстал странички Thank you для опроса и пофиксил страничку логина ( теперь их две- для стаффа и для студентов). Надо их на сервер зафигачить, потому что я так и не оч понял, как это сделать. Там несколько url файлов, и что именно в них надо добавлять - неясно #

**Comment by pollytur** [comment]
done
короче, смотри файл views.py, там есть классы, внутри которых описывается какую html мы дёргаем. Путь до html это название папки, лежащей в templates / название файла html.
например,  home_page/home_page.html

**Comment by GneyHabub** [comment]
Либо я что-то не понял, либо произошла ошибка, потому что в файле views.py нет новых файликов, там чисто опрос
